# Generated by Django 5.1.7 on 2025-03-31 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_product_date_remove_product_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductReview',
        ),
    ]
