# Generated by Django 5.1.7 on 2025-04-08 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_productreview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
